language: ruby
rvm:
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-2.1.1
  - 1.8.7



# according to the internet adding this would make Travis build go faster
# source: https://sunlightfoundation.com/blog/2015/02/24/set-up-travis-ci-for-your-ruby-application-more-quickly/

cache: bundler
sudo: false