language: ruby
rvm:
 - "1.8.7"
 - "1.9.2"
 - "1.9.3"
 - rbx
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec



# according to the internet adding this would make Travis build go faster
# source: https://sunlightfoundation.com/blog/2015/02/24/set-up-travis-ci-for-your-ruby-application-more-quickly/

cache: bundler
sudo: false